[package]
name = "h2"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[features]

# Enables **unstable** APIs. Any API exposed by this feature has no backwards
# compatibility guarantees. In other words, you should not use this feature for
# anything besides experimentation. Definitely **do not** publish a crate that
# depends on this feature.
unstable = []

[workspace]

[dependencies]
futures = "0.1"
tokio-io = "0.1.3"
tokio-timer = "0.1"
bytes = "0.4"
http = { git = "https://github.com/carllerche/http", rev = "2dd15d9" }
byteorder = "1.0"
log = "0.3.8"
fnv = "1.0.5"
slab = "0.4.0"
string = { git = "https://github.com/carllerche/string" }

[dev-dependencies]

# Support code for tests. Ideally this wouldn't be released to crates.io, but
# until rust-lang/cargo#4466 is resolved, we just have to publish this junk crate.
#
# The dependency is set on a fixed version as the `h2-test-support` offers no
# guarantees of backwards compatibility across minor versions. The version of
# `h2-test-support` should always match the current version of `h2`.
h2-test-support = { version = "= 0.1.0", path = "tests/support" }

# Fuzzing
quickcheck = "0.4.1"
rand = "0.3.15"

# HPACK fixtures
hex = "0.2.0"
walkdir = "1.0.0"
serde = "1.0.0"
serde_json = "1.0.0"

# Akamai example
tokio-core = "0.1"
env_logger = "0.4.3"
io-dump = { git = "https://github.com/carllerche/io-dump" }
rustls = "0.11"
tokio-rustls = { git = "https://github.com/briansmith/tokio-rustls", tag = "b/p1" }
webpki-roots = "0.13"
