codecov:
  notify:
    require_ci_to_pass: true
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
